[env:esp32dev]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.38-1/platform-espressif32.zip
board = esp32dev
framework = arduino
board_build.cppstd = gnu++17
board_build.f_cpu = 80000000L
board_build.partitions = huge_app.csv
monitor_speed = 115200
upload_speed = 921600
monitor_filters = esp32_exception_decoder
build_flags = -DCORE_DEBUG_LEVEL=3 -Wall -Wextra
lib_deps =
    zinggjm/GxEPD2@^1.6.9
    adafruit/Adafruit GFX Library@^1.12.6
    adafruit/Adafruit BusIO@^1.17.4
    knolleary/PubSubClient@^2.8
    ESP32Async/ESPAsyncWebServer@^3.9.6
    bblanchon/ArduinoJson@^7.4.0

[env:esp32dev-release]
extends = env:esp32dev
build_flags = -DCORE_DEBUG_LEVEL=0 -Wall -Wextra
