import { createReadStream, existsSync, statSync } from "node:fs";
import { fileURLToPath } from "node:url";
import type { Plugin } from "vite";
import { defineConfig } from "vite";
import { svelte } from "@sveltejs/vite-plugin-svelte";
import tailwindcss from "@tailwindcss/vite";

const localFactoryImage = fileURLToPath(
  new URL("../.pio/build/esp32s3-release/firmware.factory.bin", import.meta.url),
);

/**
 * Vite dev-only endpoints. Production metadata and binaries are generated by
 * scripts/generate_flasher_site.py after the app build.
 */
function localFirmwarePlugin(): Plugin {
  return {
    name: "chaya-local-firmware",
    apply: "serve",
    configureServer(server) {
      server.middlewares.use((request, response, next) => {
        const pathname = new URL(request.url ?? "/", "http://localhost").pathname;

        if (pathname === "/versions.json") {
          response.setHeader("Content-Type", "application/json");
          response.end(
            JSON.stringify({
              channels: {
                stable: {
                  channel: "stable",
                  tag: "v2026.8.1",
                  version: "dev-stable",
                  manifest: "dev/stable/manifest.json",
                  factory: "dev/firmware.factory.bin",
                },
                beta: {
                  channel: "beta",
                  tag: "v2026.8.2-rc.1",
                  version: "dev-beta",
                  manifest: "dev/beta/manifest.json",
                  factory: "dev/firmware.factory.bin",
                },
              },
            }),
          );
          return;
        }

        if (pathname === "/dev/stable/manifest.json" || pathname === "/dev/beta/manifest.json") {
          const isBeta = pathname.includes("/beta/");
          response.setHeader("Content-Type", "application/json");
          response.end(
            JSON.stringify({
              name: "Chaya2MQTT",
              version: isBeta ? "dev-beta" : "dev-stable",
              new_install_prompt_erase: true,
              new_install_improv_wait_time: 0,
              builds: [
                {
                  chipFamily: "ESP32-S3",
                  parts: [{ path: "../firmware.factory.bin", offset: 0 }],
                },
              ],
            }),
          );
          return;
        }

        if (pathname === "/dev/firmware.factory.bin") {
          if (!existsSync(localFactoryImage)) {
            response.statusCode = 404;
            response.end("Run: make build ENV=esp32s3-release");
            return;
          }
          response.setHeader("Content-Type", "application/octet-stream");
          response.setHeader("Content-Length", statSync(localFactoryImage).size);
          createReadStream(localFactoryImage).pipe(response);
          return;
        }

        next();
      });
    },
  };
}

export default defineConfig({
  // Relative URLs work on localhost and GitHub project pages (/chaya2mqtt/).
  base: "./",
  plugins: [localFirmwarePlugin(), svelte(), tailwindcss()],
  test: {
    environment: "node",
    include: ["src/**/*.test.ts"],
  },
  server: {
    host: "127.0.0.1",
    port: 4174,
  },
  preview: {
    host: "127.0.0.1",
    port: 4174,
  },
  build: {
    outDir: "dist",
    emptyOutDir: true,
    sourcemap: false,
  },
});
