#!/usr/bin/env python3
"""Build gzipped PROGMEM headers from frontend/dist for ESP32 SPA serving."""

from __future__ import annotations

import gzip
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DIST = ROOT / "frontend" / "dist"
OUT_DIR = ROOT / "src" / "web" / "assets"
MAX_TOTAL_GZ = 350 * 1024  # soft budget inside OTA flash headroom


def emit_header(name: str, symbol: str, data: bytes) -> None:
    gz = gzip.compress(data, compresslevel=9)
    lines = [
        "#pragma once",
        "",
        "#include <Arduino.h>",
        "",
        "#include <cstddef>",
        "#include <cstdint>",
        "",
        "/** Auto-generated by scripts/embed_web_assets.py — do not edit. */",
        f"inline const uint8_t {symbol}[] PROGMEM = {{",
    ]
    row: list[str] = []
    for i, b in enumerate(gz):
        row.append(f"0x{b:02x}")
        if len(row) == 16:
            lines.append("    " + ", ".join(row) + ",")
            row = []
    if row:
        lines.append("    " + ", ".join(row) + ",")
    lines.append("};")
    lines.append(f"constexpr size_t {symbol}_LEN = {len(gz)};")
    lines.append("")
    out = OUT_DIR / name
    out.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {out.relative_to(ROOT)} ({len(data)} B -> {len(gz)} B gzip)")


def main() -> int:
    required = {
        "index.html": ("spa_html.h", "SPA_INDEX_HTML_GZ"),
        "assets/app.js": ("spa_js.h", "SPA_APP_JS_GZ"),
        "assets/app.css": ("spa_css.h", "SPA_APP_CSS_GZ"),
    }
    missing = [rel for rel in required if not (DIST / rel).is_file()]
    if missing:
        print("ERROR: frontend build missing:", ", ".join(missing), file=sys.stderr)
        print("Run: cd frontend && npm ci && npm run build", file=sys.stderr)
        return 1

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    total = 0
    for rel, (header, symbol) in required.items():
        data = (DIST / rel).read_bytes()
        gz = gzip.compress(data, compresslevel=9)
        total += len(gz)
        emit_header(header, symbol, data)

    print(f"total gzip payload: {total} B")
    if total > MAX_TOTAL_GZ:
        print(
            f"ERROR: SPA assets exceed budget ({total} > {MAX_TOTAL_GZ})",
            file=sys.stderr,
        )
        return 2
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
