#!/usr/bin/env python3
"""Pack frontend/dist into an asset blob + manifest for ESP32 SPA serving.

Artifacts written to src/web/assets/:
  web_ui.bin         concatenated asset payloads
  web_ui_blob.S      .incbin stub for memory-mapped flash
  web_ui_manifest.h  path/offset/length/MIME/cache lookup table
"""

from __future__ import annotations

import gzip
import hashlib
import sys
from pathlib import Path
from typing import TypedDict

ROOT = Path(__file__).resolve().parents[1]
DIST = ROOT / "frontend" / "dist"
OUT_DIR = ROOT / "src" / "web" / "assets"
MAX_TOTAL_PAYLOAD = 350 * 1024  # soft budget inside OTA flash headroom

SKIP_NAMES = {".DS_Store", "Thumbs.db"}


class AssetEntry(TypedDict):
    """Describe one frontend asset in the generated manifest."""

    path: str
    offset: int
    length: int
    content_type: str
    cache: str


def content_type_for(path: str) -> str:
    """Return the HTTP content type for an asset path."""
    lower = path.lower()
    if lower.endswith(".html"):
        return "text/html; charset=utf-8"
    if lower.endswith((".js", ".mjs")):
        return "application/javascript; charset=utf-8"
    if lower.endswith(".css"):
        return "text/css; charset=utf-8"
    if lower.endswith(".svg"):
        return "image/svg+xml"
    if lower.endswith(".png"):
        return "image/png"
    if lower.endswith((".jpg", ".jpeg")):
        return "image/jpeg"
    if lower.endswith(".webp"):
        return "image/webp"
    if lower.endswith(".ico"):
        return "image/x-icon"
    if lower.endswith(".json"):
        return "application/json"
    if lower.endswith(".webmanifest"):
        return "application/manifest+json"
    if lower.endswith(".woff2"):
        return "font/woff2"
    if lower.endswith(".woff"):
        return "font/woff"
    if lower.endswith(".txt"):
        return "text/plain; charset=utf-8"
    return "application/octet-stream"


def cache_class_for(path: str) -> str:
    """Return the firmware cache policy for an asset path."""
    return "SpaCacheClass::Immutable" if path.startswith("/assets/") else "SpaCacheClass::NoCache"


def should_gzip(path: str) -> bool:
    """Never gzip: Safari's captive sheet mis-decodes Content-Encoding."""
    del path
    return False


def c_escape(text: str) -> str:
    """Escape text for inclusion in a C string literal."""
    return text.replace("\\", "\\\\").replace('"', '\\"')


def collect_files(src: Path) -> list[tuple[str, Path]]:
    """Collect frontend files and their corresponding URL paths."""
    files: list[tuple[str, Path]] = []
    for path in sorted(src.rglob("*")):
        if not path.is_file():
            continue
        if path.name in SKIP_NAMES:
            continue
        rel = path.relative_to(src).as_posix()
        url = "/" + rel
        files.append((url, path))
    files.sort(key=lambda item: item[0])
    return files


def dist_is_stale(dist: Path) -> bool:
    """Return whether a frontend input is newer than the Vite output."""
    outputs = [path for path in dist.rglob("*") if path.is_file()]
    if not outputs:
        return True

    frontend = dist.parent
    inputs: list[Path] = []
    for name in (
        "index.html",
        "package.json",
        "package-lock.json",
        "vite.config.ts",
        "tsconfig.json",
        "tsconfig.app.json",
    ):
        path = frontend / name
        if path.is_file():
            inputs.append(path)
    for directory in ("src", "mock"):
        root = frontend / directory
        if root.is_dir():
            inputs.extend(path for path in root.rglob("*") if path.is_file())

    oldest_output = min(path.stat().st_mtime_ns for path in outputs)
    return any(path.stat().st_mtime_ns > oldest_output for path in inputs)


def write_blob_asm(blob_path: Path) -> None:
    """Write a content-sensitive assembly stub for the embedded asset blob."""
    relative_blob = blob_path.resolve().relative_to(ROOT.resolve()).as_posix()
    blob_sha256 = hashlib.sha256(blob_path.read_bytes()).hexdigest()
    asm = f"""/* Auto-generated by scripts/embed_web_assets.py — do not edit.
 * Blob SHA-256: {blob_sha256}
 * The digest makes PlatformIO rebuild this .incbin object when the blob changes.
 */
#if defined(__APPLE__) || defined(__linux__)
    .data
    .align 4
    .global gWebUiBlobStart
gWebUiBlobStart:
    .incbin "{relative_blob}"
    .global gWebUiBlobEnd
gWebUiBlobEnd:
#else
    .section .rodata.web_ui,"a",@progbits
    .align 4
    .global gWebUiBlobStart
    .type gWebUiBlobStart, @object
gWebUiBlobStart:
    .incbin "{relative_blob}"
    .global gWebUiBlobEnd
    .type gWebUiBlobEnd, @object
gWebUiBlobEnd:
    .size gWebUiBlobStart, gWebUiBlobEnd - gWebUiBlobStart
#endif
    .align 4
"""
    (OUT_DIR / "web_ui_blob.S").write_text(asm, encoding="utf-8")


def write_index_literal(index_html: bytes) -> list[str]:
    """Emit index.html as a compiler string so / always has a real DOCTYPE."""
    text = index_html.decode("utf-8")
    if ")chayaINDEX" in text:
        raise ValueError("index.html contains the embed delimiter")
    return [
        "/** Exact Vite index.html; not sliced from the .incbin blob. */",
        'inline constexpr char kWebUiIndexHtml[] = R"chayaINDEX(',
        text,
        ')chayaINDEX";',
        "",
    ]


def write_manifest(entries: list[AssetEntry], index_html: bytes) -> None:
    """Write the C++ lookup table for compressed frontend assets."""
    lines = [
        "#pragma once",
        "",
        "#include <cstddef>",
        "#include <cstdint>",
        "",
        '#include "web/spa_asset_lookup.h"',
        "",
        "/** Auto-generated by scripts/embed_web_assets.py — do not edit. */",
        'extern "C" const uint8_t gWebUiBlobStart[];',
        'extern "C" const uint8_t gWebUiBlobEnd[];',
        "",
        *write_index_literal(index_html),
        "inline const SpaAssetEntry WEB_UI_ASSETS[] = {",
    ]
    if not entries:
        lines.append('    {"", 0u, 0u, "application/octet-stream", SpaCacheClass::NoCache},')
    else:
        lines.extend(
            [
                '    {{"{path}", {offset}u, {length}u, "{ct}", {cache}}},'.format(
                    path=c_escape(entry["path"]),
                    offset=entry["offset"],
                    length=entry["length"],
                    ct=c_escape(entry["content_type"]),
                    cache=entry["cache"],
                )
                for entry in entries
            ]
        )
    lines.extend(
        [
            "};",
            "",
            f"constexpr size_t WEB_UI_ASSETS_COUNT = {len(entries)}u;",
            "",
        ]
    )
    (OUT_DIR / "web_ui_manifest.h").write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    """Compress frontend assets and generate firmware embedding files."""
    if not DIST.is_dir():
        print(
            "ERROR: frontend/dist missing. Run: cd frontend && npm ci && npm run build",
            file=sys.stderr,
        )
        return 1
    if dist_is_stale(DIST):
        print(
            "ERROR: frontend/dist is stale. Run: cd frontend && npm run build",
            file=sys.stderr,
        )
        return 3

    files = collect_files(DIST)
    index_files = [path for path, _ in files if path == "/index.html"]
    if not index_files:
        print("ERROR: frontend/dist/index.html missing", file=sys.stderr)
        return 1
    index_html = next(fp.read_bytes() for url, fp in files if url == "/index.html")

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    blob = bytearray()
    entries: list[AssetEntry] = []

    for url_path, file_path in files:
        raw = file_path.read_bytes()
        payload = gzip.compress(raw, compresslevel=9) if should_gzip(url_path) else raw
        entries.append(
            {
                "path": url_path,
                "offset": len(blob),
                "length": len(payload),
                "content_type": content_type_for(url_path),
                "cache": cache_class_for(url_path),
            }
        )
        blob.extend(payload)
        kind = "gzip" if should_gzip(url_path) else "raw"
        print(f"packed {url_path} ({len(raw)} B -> {len(payload)} B {kind})")

    if not blob:
        blob.append(0)

    total = sum(e["length"] for e in entries)
    print(f"total embedded payload: {total} B ({len(entries)} files)")
    if total > MAX_TOTAL_PAYLOAD:
        print(
            f"ERROR: SPA assets exceed budget ({total} > {MAX_TOTAL_PAYLOAD})",
            file=sys.stderr,
        )
        return 2

    blob_path = OUT_DIR / "web_ui.bin"
    blob_path.write_bytes(bytes(blob))
    write_blob_asm(blob_path)
    write_manifest(entries, index_html)

    def rel(path: Path) -> str:
        try:
            return str(path.relative_to(ROOT))
        except ValueError:
            return str(path)

    print(f"wrote {rel(blob_path)}")
    print(f"wrote {rel(OUT_DIR / 'web_ui_blob.S')}")
    print(f"wrote {rel(OUT_DIR / 'web_ui_manifest.h')}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
