#!/usr/bin/env python3
"""Pack frontend/dist into a gzip blob + manifest for ESP32 SPA serving.

Artifacts written to src/web/assets/:
  web_ui.bin         concatenated gzip payloads
  web_ui_blob.S      .incbin stub for memory-mapped flash
  web_ui_manifest.h  path/offset/length/MIME/cache lookup table
"""

from __future__ import annotations

import gzip
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DIST = ROOT / "frontend" / "dist"
OUT_DIR = ROOT / "src" / "web" / "assets"
MAX_TOTAL_GZ = 350 * 1024  # soft budget inside OTA flash headroom

SKIP_NAMES = {".DS_Store", "Thumbs.db"}


def content_type_for(path: str) -> str:
    lower = path.lower()
    if lower.endswith(".html"):
        return "text/html; charset=utf-8"
    if lower.endswith(".js") or lower.endswith(".mjs"):
        return "application/javascript; charset=utf-8"
    if lower.endswith(".css"):
        return "text/css; charset=utf-8"
    if lower.endswith(".svg"):
        return "image/svg+xml"
    if lower.endswith(".png"):
        return "image/png"
    if lower.endswith(".jpg") or lower.endswith(".jpeg"):
        return "image/jpeg"
    if lower.endswith(".webp"):
        return "image/webp"
    if lower.endswith(".ico"):
        return "image/x-icon"
    if lower.endswith(".json"):
        return "application/json"
    if lower.endswith(".webmanifest"):
        return "application/manifest+json"
    if lower.endswith(".woff2"):
        return "font/woff2"
    if lower.endswith(".woff"):
        return "font/woff"
    if lower.endswith(".txt"):
        return "text/plain; charset=utf-8"
    return "application/octet-stream"


def cache_class_for(path: str) -> str:
    return "SpaCacheClass::Immutable" if path.startswith("/assets/") else "SpaCacheClass::NoCache"


def c_escape(text: str) -> str:
    return text.replace("\\", "\\\\").replace('"', '\\"')


def collect_files(src: Path) -> list[tuple[str, Path]]:
    files: list[tuple[str, Path]] = []
    for path in sorted(src.rglob("*")):
        if not path.is_file():
            continue
        if path.name in SKIP_NAMES:
            continue
        rel = path.relative_to(src).as_posix()
        url = "/" + rel
        files.append((url, path))
    files.sort(key=lambda item: item[0])
    return files


def write_blob_asm(blob_path: Path) -> None:
    abs_blob = blob_path.resolve().as_posix()
    asm = f"""/* Auto-generated by scripts/embed_web_assets.py — do not edit. */
#if defined(__APPLE__) || defined(__linux__)
    .data
#else
    .section .rodata.embedded
#endif
    .align 4
    .global gWebUiBlobStart
gWebUiBlobStart:
    .incbin "{abs_blob}"
    .global gWebUiBlobEnd
gWebUiBlobEnd:
    .align 4
"""
    (OUT_DIR / "web_ui_blob.S").write_text(asm, encoding="utf-8")


def write_manifest(entries: list[dict]) -> None:
    lines = [
        "#pragma once",
        "",
        "#include <cstddef>",
        "#include <cstdint>",
        "",
        '#include "web/spa_asset_lookup.h"',
        "",
        "/** Auto-generated by scripts/embed_web_assets.py — do not edit. */",
        "extern const uint8_t gWebUiBlobStart[];",
        "extern const uint8_t gWebUiBlobEnd[];",
        "",
        "inline const SpaAssetEntry WEB_UI_ASSETS[] = {",
    ]
    if not entries:
        lines.append(
            '    {"", 0u, 0u, "application/octet-stream", SpaCacheClass::NoCache},'
        )
    else:
        for entry in entries:
            lines.append(
                '    {{"{path}", {offset}u, {length}u, "{ct}", {cache}}},'.format(
                    path=c_escape(entry["path"]),
                    offset=entry["offset"],
                    length=entry["length"],
                    ct=c_escape(entry["content_type"]),
                    cache=entry["cache"],
                )
            )
    lines.extend(
        [
            "};",
            "",
            f"constexpr size_t WEB_UI_ASSETS_COUNT = {len(entries)}u;",
            "",
        ]
    )
    (OUT_DIR / "web_ui_manifest.h").write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    if not DIST.is_dir():
        print("ERROR: frontend/dist missing. Run: cd frontend && npm ci && npm run build", file=sys.stderr)
        return 1

    files = collect_files(DIST)
    if not any(path == "/index.html" for path, _ in files):
        print("ERROR: frontend/dist/index.html missing", file=sys.stderr)
        return 1

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    blob = bytearray()
    entries: list[dict] = []

    for url_path, file_path in files:
        raw = file_path.read_bytes()
        gz = gzip.compress(raw, compresslevel=9)
        entries.append(
            {
                "path": url_path,
                "offset": len(blob),
                "length": len(gz),
                "content_type": content_type_for(url_path),
                "cache": cache_class_for(url_path),
            }
        )
        blob.extend(gz)
        print(f"packed {url_path} ({len(raw)} B -> {len(gz)} B gzip)")

    if not blob:
        blob.append(0)

    total = sum(e["length"] for e in entries)
    print(f"total gzip payload: {total} B ({len(entries)} files)")
    if total > MAX_TOTAL_GZ:
        print(
            f"ERROR: SPA assets exceed budget ({total} > {MAX_TOTAL_GZ})",
            file=sys.stderr,
        )
        return 2

    blob_path = OUT_DIR / "web_ui.bin"
    blob_path.write_bytes(bytes(blob))
    write_blob_asm(blob_path)
    write_manifest(entries)

    def rel(path: Path) -> str:
        try:
            return str(path.relative_to(ROOT))
        except ValueError:
            return str(path)

    print(f"wrote {rel(blob_path)}")
    print(f"wrote {rel(OUT_DIR / 'web_ui_blob.S')}")
    print(f"wrote {rel(OUT_DIR / 'web_ui_manifest.h')}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
